FROM node:22.16.0

WORKDIR /application

COPY  package.json .

COPY package-lock.json .

RUN npm i --legacy-peer-deps 

COPY . .

RUN npm run build 


CMD [ "npm", "start", "--", "--port", "3100" ]

EXPOSE 3100 
