services:
  

  mongo:
    image: mongo
    ports:
      - "27019:27017"
    networks: 
      - url_net
  backend: 
    build: 
      context: ./backend
    env_file:
      - .env
    ports:
      - "8500:8500"
    depends_on:
      - mongo
    networks:
      - url_net
      
  frontend: 
    build: 
      context: ./frontend
    env_file:
      - .env
    networks:
      - url_net
    ports: 
      - "3100:3100"

  
networks:
  url_net: 
    driver : bridge