FROM python:3.11.13

WORKDIR /backend

COPY . .

RUN apt-get update && apt-get install -y --no-install-recommends curl ca-certificates

# Download the latest installer
ADD https://astral.sh/uv/install.sh /uv-installer.sh

# Run the installer then remove it
RUN sh /uv-installer.sh && rm /uv-installer.sh

# Ensure the installed binary is on the `PATH`
ENV PATH="/root/.local/bin/:$PATH"

RUN uv venv .venv 
RUN uv sync
RUN uv pip install -e . 

CMD [ "uv", "run", "uvicorn", "src.url_shortener_app.main:app", "--host", "0.0.0.0", "--port", "8500"]